<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class ImageService
{
    protected OpenAIService $openAI;

    protected ?string $unsplashAccessKey;

    public function __construct()
    {
        $this->openAI = app(OpenAIService::class);
        $this->unsplashAccessKey = config('services.unsplash.access_key');
    }

    /**
     * Get a featured image for an article. Tries Unsplash first, falls back to DALL-E.
     */
    public function getFeaturedImage(string $topic, string $articleTitle, string $articleExcerpt): array
    {
        // Try Unsplash first
        $unsplashResult = $this->searchUnsplash($topic);
        if ($unsplashResult) {
            return $unsplashResult;
        }

        // Fall back to DALL-E
        return $this->generateWithDalle($articleTitle, $articleExcerpt);
    }

    /**
     * Search Unsplash for a relevant image.
     */
    protected function searchUnsplash(string $query): ?array
    {
        if (empty($this->unsplashAccessKey)) {
            return null;
        }

        try {
            $response = Http::timeout(10)
                ->withHeaders([
                    'Authorization' => "Client-ID {$this->unsplashAccessKey}",
                ])
                ->get('https://api.unsplash.com/search/photos', [
                    'query' => $query,
                    'orientation' => 'landscape',
                    'per_page' => 5,
                    'content_filter' => 'high',
                ]);

            if (!$response->successful()) {
                Log::warning("Unsplash search failed: {$response->status()}");
                return null;
            }

            $data = $response->json();

            if (empty($data['results'])) {
                return null;
            }

            $photo = $data['results'][0];

            return [
                'url' => $photo['urls']['regular'],
                'credit' => $photo['user']['name'],
                'credit_url' => $photo['user']['links']['html'],
                'source' => 'unsplash',
            ];
        } catch (\Throwable $e) {
            Log::warning("Unsplash search error: {$e->getMessage()}");
            return null;
        }
    }

    /**
     * Generate an image using DALL-E.
     */
    protected function generateWithDalle(string $articleTitle, string $articleExcerpt): array
    {
        try {
            $prompt = $this->openAI->generateImagePrompt($articleTitle, $articleExcerpt);
            $imageUrl = $this->openAI->generateDalleImage($prompt);

            if ($imageUrl) {
                return [
                    'url' => $imageUrl,
                    'credit' => 'Generated by AI',
                    'credit_url' => null,
                    'source' => 'dalle',
                ];
            }

            // Ultimate fallback - placeholder
            return [
                'url' => '/images/placeholder-news.jpg',
                'credit' => null,
                'credit_url' => null,
                'source' => 'placeholder',
            ];
        } catch (\Throwable $e) {
            Log::warning("DALL-E generation failed: {$e->getMessage()}");
            return [
                'url' => '/images/placeholder-news.jpg',
                'credit' => null,
                'credit_url' => null,
                'source' => 'placeholder',
            ];
        }
    }
}
