<?php

namespace App\Filament\Resources\ApiPartners\Schemas;

use Filament\Forms\Components\Placeholder;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class ApiPartnerForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Partner Details')
                    ->columns(2)
                    ->schema([
                        TextInput::make('name')
                            ->label('Partner / Website Name')
                            ->required()
                            ->maxLength(100),
                        TextInput::make('website_url')
                            ->label('Website URL')
                            ->url()
                            ->maxLength(255),
                        Toggle::make('is_active')
                            ->label('Active')
                            ->default(true)
                            ->inline(false),
                        Textarea::make('notes')
                            ->label('Internal Notes')
                            ->rows(2)
                            ->maxLength(500)
                            ->columnSpanFull(),
                    ]),

                Section::make('API Key')
                    ->columns(1)
                    ->schema([
                        // On create: show auto-generated key (read-only, generated by observer)
                        Placeholder::make('api_key_info')
                            ->label('API Key')
                            ->content('API key is auto-generated when partner is created. View it on the edit page.')
                            ->visibleOn('create'),

                        // On edit: show actual key
                        TextInput::make('api_key')
                            ->label('API Key')
                            ->disabled()
                            ->copyable()
                            ->helperText('Share this key with the partner. They send it as X-API-Key header.')
                            ->visibleOn('edit'),
                    ]),
            ]);
    }
}
